FROM maven as base
WORKDIR /usr/src/mymaven
COPY ../ .
RUN mvn clean package -Dmaven.test.skip


FROM --platform=linux/arm64 openjdk

WORKDIR /app
COPY ./static ./static
COPY --from=base /usr/src/mymaven/target/lavajato-api-0.0.1-SNAPSHOT.jar ./app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]