FROM maven as base
WORKDIR /usr/src/mymaven
COPY ../ .
RUN mvn clean package -Dmaven.test.skip


FROM openjdk

WORKDIR /app
COPY --from=base /usr/src/mymaven/target/app-0.0.1-SNAPSHOT.jar ./app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]