name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file docker/Dockerfile-prod --tag latest


      - name: Publish to Registry
        uses: minddocdev/docker-publish-action@master
        with:
          name: imrayh/temp
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: docker/Dockerfile-prod